project:
  type: website

website:
  title: "Naotaka Shigeta"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: beyond-research.qmd
        text: Beyond Research
      - href: link.qmd
        text: Links
    right:
      - icon: github
        href: https://github.com/naotaka-shigeta
  search: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
